server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config‐location: classpath:mybatis/mybatisConfig.xml
#redis:
#  config‐location: classpath:/redisson-config.yml